WITH ORG_INFO AS (
      SELECT ID_ORG, INN
      FROM ORGANIZATIONS
      WHERE CLIENT_NAME = 'Наименование организации'
),
CREDIT_RATE_AVG AS (
      SELECT AVG(CREDIT_RATE) AS CREDIT_RATE_AVERAGE
      FROM CREDIT_Portfolio
      WHERE INN = (SELECT INN FROM ORG_INFO)
),
DOCS_VALUE AS (
      SELECT DD.NM
      FROM DOCS_Numbers DN INNER JOIN DOCS_Data DD ON DN.ID_DOCS = DD.ID_DOCS
      WHERE DN.DOCS_TYPE = 'Финансовая отчетность'  AND 
            DN.CODE = (SELECT ID_ORG FROM ORG_INFO) AND 
            DD.ROW_DOCS = 2000
)
SELECT (SELECT NM FROM DOCS_VALUE) AS row_value,
       (SELECT CREDIT_RATE_AVERAGE FROM CREDIT_RATE_AVG) AS credit_rate_avg;
